# Site
repository: fhasni/cv # Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: HASNI Faiçal
title: Senior Software Engineer
email: hasni.faissal@gmail.com
phone: +212 6 96 18 00 72
website: https://hasni.xyz

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: FaicalHasni
github_username: fhasni
stackoverflow_username: "3754143"
#dribbble_username: fhasni
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: fhasni
xing_username: Hasni_Faical
#pinterest_username: faicalhasni
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0001-7087-8204

# Additional icon links
additional_links:
# - title: Indeed
#   icon: fa-indeed is not available on font awesome to check later
#   url: https://my.indeed.com/p/faialh-can8hcq
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-177858292-1"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/img/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Faiçal HASNI, I am a Senior Software Engineer with a State Engineer Degree in Telecommunication and Information Technology (M.Sc.I.T.) from The National Institute of Posts and Telecommunications of Rabat.

  With more than 6 years of professional experience in IT, where I had hands-on software design, DevOps, cloud computing, and full-stack development, And where I contributed to the digital transformation of multiple industries such as healthcare and banking.

  I enjoy being challenged and working on projects that require working outside my comfort and knowledge set.

  Core skills:
    - Talented in leadership
    - Skilled in Architecting, Developing, Testing and troubleshooting software
    - Thorough understanding of data structures and algorithms
    - Knowledgeable of back-end and front-end development best practices

  Expertise:
    <mark>Agile Methodologies</mark> <mark>Software Development</mark> <mark>Information Security</mark> <mark>Multimedia</mark> <mark>Swift</mark> <mark>Objective-C</mark> <mark>PHP</mark> <mark>JavaScript</mark> <mark>TypeScript</mark> <mark>Go</mark> <mark>Java</mark> <mark>C# SQL</mark> <mark>Git</mark> <mark>Docker</mark> <mark>Jenkins</mark> <mark>Grafana</mark> <mark>Amazon Web Services (AWS)</mark> <mark>Linux</mark> <mark>Angular</mark> <mark>AngularJS</mark> <mark>Node.js</mark> <mark>Parse server</mark> <mark>Angular</mark> <mark>REST API</mark> <mark>MySQL</mark> <mark>SQL Server</mark> <mark>MongoDB</mark> <mark>CouchDB</mark> <mark>Microservices</mark> <mark>Continuous Integration and Continuous Delivery (CI/CD)</mark> <mark>Clean architecture</mark> <mark>MVC</mark> <mark>MVP</mark> <mark>MVVM</mark> <mark>VIP</mark> <mark>VIPER</mark>

# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Experience #(Use this to override about experience section title)

# Education Section
education_title: Education #(Use this to override about education section title)

# More Section
more_title: More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Languages skills**
    - Arabic: Native
    - English: Professional
    - French: Professional

  **Interests:**
    - Science
    - Gaming
    - IT Geeks

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
